sudo: required

services:
  - docker

language: python
python:
  - 3.8

install:
  - cd invoice-service/
  - pip install -r requirements.txt

jobs:
  include:
    - stage: tests
    name: "Unit Tests"
    script:
      - python -m unittest discover -s "." -p "*_test.py"

after_success:
  - sh .travis/deploy_dockerhub.sh
