version: '3.8'
services:
  employee-frontend:
    build:
      context: employee-frontend
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    depends_on:
      - invoice-service

  employer-frontend:
    build:
      context: employer-frontend
      dockerfile: Dockerfile
    ports:
      - '8082:8080'
    depends_on:
      - invoice-service

  invoice-service:
    build:
      context: ./invoice-service
    ports:
      - '5000:5000'
    depends_on:
      - mongo 

  mongo:
    image: 'mongo:4.2-bionic'
    deploy:
      restart_policy:
        condition: always
    ports:
      - '27017:27017'
